### ISSUE TITLE
build_service.sh not work in ubuntu 14.04

### ISSUE THREAD

**Issue by ZYecho** [oncecloud/cStack-utility#1]
构建基础镜像过程中报错，某些dockerfile,如base12.04中含有RUN wget https://github.com/Treeptik/cloudunit/releases/download/1.0/cloudunitAgent-1.0-SNAPSHOT.jar -O /cloudunit/tools/cloudunitAgent-1.0-SNAPSHOT.jar， 此链接已失效。

**Comment by net613** [comment]
I have fixed it, pls try again.
